version: '3.7'

services:

## mongo db connection with replicSet
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ulib
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    command: mongod --replSet rs0 --bind_ip_all 

    

  # app:
  #   image: ulibrary-api
  #   container_name: app
  #   depends_on:
  #     - db
  #   environment:
  #     PORT: 4000
  #     JWT_SECRET: #u!V6V%qJk5%^7UKaIvevrq(*xwcY%U8+
  #     DATABASE_URL: postgresql://user:password@db:5432/ulib?schema=public
  #   ports:
  #     - '4000:4000'
